//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _99xAssessment2.Repository.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountJournal
    {
        public long Id { get; set; }
        public long InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedAt { get; set; }
        public long AccountId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public decimal Value { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual User User { get; set; }
    }
}
